import { blue, green, grey, red } from "@ant-design/colors";
import { getCurrentMonthDate } from "@crema/helpers/DateHelper";
import { TodoObjType } from "@crema/types/models/apps/Todo";

const todoList: TodoObjType[] = [
  {
    id: 456753,
    title: "Surveillance Оптимизация",
    priority: { id: 4545554, name: "Высокий", type: 1, color: red[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
    ],
    isAttachment: true,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(29),
    endDate: getCurrentMonthDate(31),
    scheduleMobile: "5:30 PM",
    folderValue: 121,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 503,
      name: "Абдуганиев Отабек",
      image: "/assets/images/avatar/A111.jpg",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(26),
    status: 1003,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Rohit Sharma",
        image: "/assets/images/avatar/A22.jpg",
        date: getCurrentMonthDate(30),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 435544534,
    title: "Добавить раздел 'доходы' в профиле эмитентов",
    priority: { id: 9384234, name: "Средний", type: 2, color: blue[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(3),
    endDate: getCurrentMonthDate(6),
    scheduleMobile: "8:30 PM",
    folderValue: 124,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 505,
      name: "Зарифбоев Абдулазиз",
      image: "/assets/images/avatar/A112.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(18),
    status: 1002,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Narendra Kumar",
        image: "/assets/images/avatar/A11.jpg",
        date: "Dec 21, 2021",
        time: "4:18am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 783232,
    title: "Закончить переводы на русский",
    isStarred: true,
    label: [
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
      {
        id: 212,
        name: "Admin Panel",
        alias: "css",
        label: "CSS",
        value: "CSS",
        color: blue[5],
      },
    ],
    priority: { id: 4545554, name: "Высокий", type: 1, color: red[5] },
    isAttachment: false,
    sentAt: "10.30am",
    folderValue: 121,
    startDate: getCurrentMonthDate(18),
    endDate: getCurrentMonthDate(22),
    scheduleMobile: "8:30 PM",
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 501,
      name: "Расулжанов Кобулжон",
      image: "/assets/images/avatar/A113.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(12),
    status: 1001,
    comments: [
      {
        comment:
          "The Task is very important, try to complete it so that we have time for testing.",
        name: "K L Sharma",
        image: "/assets/images/avatar/A21.jpg",
        date: getCurrentMonthDate(20),
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 32432435,
    title: "Добавить портфель инвестора",
    isStarred: true,
    label: [
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
      {
        id: 212,
        name: "Admin Panel",
        alias: "css",
        label: "CSS",
        value: "CSS",
        color: blue[5],
      },
    ],
    priority: { id: 4545554, name: "Высокий", type: 1, color: red[5] },
    isAttachment: false,
    sentAt: "10.30am",
    folderValue: 121,
    startDate: getCurrentMonthDate(30),
    endDate: getCurrentMonthDate(1),
    scheduleMobile: "8:30 PM",
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 501,
      name: "Бекмирзаев Жасурбек",
      image: "/assets/images/avatar/A114.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(26),
    status: 1001,
    comments: [
      {
        comment:
          "The Task is very important, try to complete it so that we have time for testing.",
        name: "K L Sharma",
        image: "/assets/images/avatar/A21.jpg",
        date: getCurrentMonthDate(28),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 454553,
    title: "next.openinfo.uz замечания и предложения",
    priority: { id: 9384234, name: "Средний", type: 2, color: blue[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(19),
    endDate: getCurrentMonthDate(22),
    scheduleMobile: "7:30 PM",
    folderValue: 123,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 502,
      name: "Каримов Диербек",
      image: "/assets/images/avatar/A115.jpg",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(10),
    status: 1002,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "M S Dhoni",
        image: "/assets/images/avatar/A1.jpg",
        date: getCurrentMonthDate(25),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 5467454354,
    title: "Добавить автоматический формат цифр в фин.отчете",
    priority: { id: 9384234, name: "Средний", type: 2, color: blue[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(9),
    endDate: getCurrentMonthDate(12),
    scheduleMobile: "7:30 PM",
    folderValue: 123,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 502,
      name: "Абдуганиев Отабек",
      image: "/assets/images/avatar/A111.jpg",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(26),
    status: 1002,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "M S Dhoni",
        image: "/assets/images/avatar/A1.jpg",
        date: getCurrentMonthDate(28),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 345655,
    title: "Создать базу данных описаний для ИИ",
    priority: { id: 4354454, name: "Низкий", type: 3, color: green[5] },
    isStarred: false,
    isReplied: false,
    label: [
      {
        id: 214,
        name: "openInfo/ModeratorMode",
        alias: "node",
        label: "Node.js",
        value: "Node.js",
        color: grey[5],
      },
    ],
    isAttachment: true,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(2),
    endDate: getCurrentMonthDate(4),
    scheduleMobile: "6:30 PM",
    isRead: true,
    folderValue: 124,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 503,
      name: "Зарифбоев Абдулазиз",
      image: "/assets/images/avatar/A112.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(19),
    status: 1003,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Nikit Sharma",
        image: "/assets/images/avatar/A2.jpg",
        date: getCurrentMonthDate(21),
        time: "2:15am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 5432356454,
    title: "Правки к 36-факту в openinfo",
    priority: { id: 4354454, name: "Низкий", type: 3, color: green[5] },
    isStarred: false,
    isReplied: false,
    label: [
      {
        id: 214,
        name: "openInfo/ModeratorMode",
        alias: "node",
        label: "Node.js",
        value: "Node.js",
        color: grey[5],
      },
    ],
    isAttachment: true,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(6),
    endDate: getCurrentMonthDate(12),
    scheduleMobile: "4:30 PM",
    isRead: true,
    folderValue: 124,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 503,
      name: "Расулжанов Кобулжон",
      image: "/assets/images/avatar/A113.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(25),
    status: 1003,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Nikit Sharma",
        image: "/assets/images/avatar/A2.jpg",
        date: getCurrentMonthDate(27),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 765645,
    title: "Добавить функцию баланса к каждой акции",
    priority: { id: 9384234, name: "Средний", type: 2, color: blue[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(15),
    endDate: getCurrentMonthDate(18),
    scheduleMobile: "5:30 PM",
    folderValue: 211,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 504,
      name: "Бекмирзаев Жасурбек",
      image: "/assets/images/avatar/A114.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(12),
    status: 1001,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Ravindra Jadeja",
        image: "/assets/images/avatar/A4.jpg",
        date: getCurrentMonthDate(22),
        time: "2:35am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 4324543234,
    title: "Правки по переводу",
    priority: { id: 9384234, name: "Средний", type: 2, color: blue[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(26),
    endDate: getCurrentMonthDate(29),
    scheduleMobile: "8:30 PM",
    folderValue: 211,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 504,
      name: "Каримов Диербек",
      image: "/assets/images/avatar/A115.jpg",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(22),
    status: 1001,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Ravindra Jadeja",
        image: "/assets/images/avatar/A4.jpg",
        date: getCurrentMonthDate(26),
        time: "4:18am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 765635,
    title: "Подключить счет инвестора к электронной почте",
    priority: { id: 4545554, name: "Высокий", type: 1, color: red[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
      {
        id: 212,
        name: "Admin Panel",
        alias: "css",
        label: "CSS",
        value: "CSS",
        color: blue[5],
      },
    ],
    isAttachment: true,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(13),
    endDate: getCurrentMonthDate(15),
    scheduleMobile: "9:30 PM",
    folderValue: 121,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 505,
      name: "Абдуганиев Отабек",
      image: "/assets/images/avatar/A111.jpg",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(9),
    status: 1002,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Krishna Kumar",
        image: "/assets/images/avatar/A5.jpg",
        date: getCurrentMonthDate(19),
        time: "2:45am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 345536,
    title: "Поменять млн.сум на  на тыс.сум",
    priority: { id: 4354454, name: "Низкий", type: 3, color: green[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 212,
        name: "Admin Panel",
        alias: "css",
        label: "CSS",
        value: "CSS",
        color: blue[5],
      },
      {
        id: 214,
        name: "openInfo/ModeratorMode",
        alias: "node",
        label: "Node.js",
        value: "Node.js",
        color: grey[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(13),
    endDate: getCurrentMonthDate(15),
    scheduleMobile: "8:30 PM",
    folderValue: 126,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 506,
      name: "Зарифбоев Абдулазиз",
      image: "/assets/images/avatar/A112.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(8),
    status: 1003,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Rehan Kant",
        image: "/assets/images/avatar/A6.jpg",
        date: getCurrentMonthDate(18),
        time: "10:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 654343443,
    title: "Поменять расчет процента в учетном регистре",
    priority: { id: 4545554, name: "Высокий", type: 1, color: red[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
      {
        id: 212,
        name: "Admin Panel",
        alias: "css",
        label: "CSS",
        value: "CSS",
        color: blue[5],
      },
    ],
    isAttachment: true,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(23),
    endDate: getCurrentMonthDate(25),
    scheduleMobile: "7:30 PM",
    folderValue: 121,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 505,
      name: "Расулжанов Кобулжон",
      image: "/assets/images/avatar/A113.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(22),
    status: 1002,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Krishna Kumar",
        image: "/assets/images/avatar/A5.jpg",
        date: getCurrentMonthDate(26),
        time: "4:18am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 785655,
    title: "Добавить номер лицензии к отчету по сотрудникам",
    priority: { id: 9384234, name: "Средний", type: 2, color: blue[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(12),
    endDate: getCurrentMonthDate(15),
    scheduleMobile: "7:30 PM",
    folderValue: 124,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 501,
      name: "Бекмирзаев Жасурбек",
      image: "/assets/images/avatar/A114.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(7),
    status: 1001,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Rahul Rajan",
        image: "/assets/images/avatar/A7.jpg",
        date: getCurrentMonthDate(21),
        time: "7:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 234554,
    title: "Правки по e.docs api",
    priority: { id: 4354454, name: "Низкий", type: 3, color: green[5] },
    isStarred: false,
    isReplied: false,
    label: [
      {
        id: 214,
        name: "openInfo/ModeratorMode",
        alias: "node",
        label: "Node.js",
        value: "Node.js",
        color: grey[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(12),
    endDate: getCurrentMonthDate(14),
    scheduleMobile: "5:30 PM",
    folderValue: 125,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 502,
      name: "Каримов Диербек",
      image: "/assets/images/avatar/A115.jpg",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(7),
    status: 1002,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Shikhar Dhawan",
        image: "/assets/images/avatar/A8.jpg",
        date: getCurrentMonthDate(22),
        time: "2:12am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 86764543,
    title: "Добавить доп.аттрибуты в openinfo",
    priority: { id: 4354454, name: "Низкий", type: 3, color: green[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 212,
        name: "Admin Panel",
        alias: "css",
        label: "CSS",
        value: "CSS",
        color: blue[5],
      },
      {
        id: 214,
        name: "openInfo/ModeratorMode",
        alias: "node",
        label: "Node.js",
        value: "Node.js",
        color: grey[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(24),
    endDate: getCurrentMonthDate(26),
    scheduleMobile: "7:30 PM",
    folderValue: 126,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 506,
      name: "Абдуганиев Отабек",
      image: "/assets/images/avatar/A111.jpg",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(22),
    status: 1003,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Rehan Kant",
        image: "/assets/images/avatar/A6.jpg",
        date: getCurrentMonthDate(18),
        time: "4:18am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 907645,
    title: "Нарисовать внутренние таблицы в Securities Issuance",
    priority: { id: 4545554, name: "Высокий", type: 1, color: red[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
      {
        id: 214,
        name: "openInfo/ModeratorMode",
        alias: "node",
        label: "Node.js",
        value: "Node.js",
        color: grey[5],
      },
    ],
    isAttachment: true,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(10),
    endDate: getCurrentMonthDate(12),
    scheduleMobile: "4:30 PM",
    folderValue: 121,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 503,
      name: "Зарифбоев Абдулазиз",
      image: "/assets/images/avatar/A112.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(6),
    status: 1003,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "shreyas Iyer",
        image: "/assets/images/avatar/A9.jpg",
        date: getCurrentMonthDate(18),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 678434,
    title: "Добавить портфель инвестора",
    priority: { id: 4545554, name: "Высокий", type: 1, color: red[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 212,
        name: "Admin Panel",
        alias: "css",
        label: "CSS",
        value: "CSS",
        color: blue[5],
      },
      {
        id: 214,
        name: "openInfo/ModeratorMode",
        alias: "node",
        label: "Node.js",
        value: "Node.js",
        color: grey[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    folderValue: 125,
    startDate: getCurrentMonthDate(9),
    endDate: getCurrentMonthDate(10),
    scheduleMobile: "8:30 PM",
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 504,
      name: "Расулжанов Кобулжон",
      image: "/assets/images/avatar/A113.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(1),
    status: 1001,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Bhuvneshwar Kumar",
        image: "/assets/images/avatar/A10.jpg",
        date: getCurrentMonthDate(18),
        time: "2:55am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 2344344334,
    title: "Подготовка фронт. части CRUD и подключение  к api",
    priority: { id: 9384234, name: "Средний", type: 2, color: blue[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(23),
    endDate: getCurrentMonthDate(26),
    scheduleMobile: "6:30 PM",
    folderValue: 124,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 501,
      name: "Бекмирзаев Жасурбек",
      image: "/assets/images/avatar/A114.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(18),
    status: 1001,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Rahul Rajan",
        image: "/assets/images/avatar/A7.jpg",
        date: getCurrentMonthDate(24),
        time: "4:18am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 789754,
    title: "Правки по etender.uzex.uz",
    priority: { id: 9384234, name: "Средний", type: 2, color: blue[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(8),
    endDate: getCurrentMonthDate(10),
    scheduleMobile: "6:30 PM",
    folderValue: 124,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 505,
      name: "Каримов Диербек",
      image: "/assets/images/avatar/A115.jpg",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(5),
    status: 1002,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Narendra Kumar",
        image: "/assets/images/avatar/A11.jpg",
        date: getCurrentMonthDate(18),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 345656,
    title: "Check the documents of audit",
    priority: { id: 4354454, name: "Низкий", type: 3, color: green[5] },
    isStarred: false,
    isReplied: false,
    label: [],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(2),
    endDate: getCurrentMonthDate(5),
    scheduleMobile: "6:30 PM",
    folderValue: 123,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 506,
      name: "Абдуганиев Отабек",
      image: "/assets/images/avatar/A111.jpg",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(2),
    status: 1003,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Baichang Bhutia",
        image: "/assets/images/avatar/A13.jpg",
        date: getCurrentMonthDate(22),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 767643433,
    title: "Schedule an interview for hiring React developer",
    priority: { id: 4354454, name: "Низкий", type: 3, color: green[5] },
    isStarred: false,
    isReplied: false,
    label: [
      {
        id: 214,
        name: "openInfo/ModeratorMode",
        alias: "node",
        label: "Node.js",
        value: "Node.js",
        color: grey[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(1),
    endDate: getCurrentMonthDate(2),
    scheduleMobile: "5:30 PM",
    folderValue: 125,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 502,
      name: "Зарифбоев Абдулазиз",
      image: "/assets/images/avatar/A112.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(21),
    status: 1002,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Shikhar Dhawan",
        image: "/assets/images/avatar/A8.jpg",
        date: getCurrentMonthDate(25),
        time: "4:18am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 856787,
    title: "Arrange birthday party for the staff",
    priority: { id: 9384234, name: "Средний", type: 2, color: blue[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
      {
        id: 212,
        name: "Admin Panel",
        alias: "css",
        label: "CSS",
        value: "CSS",
        color: blue[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(6),
    endDate: getCurrentMonthDate(8),
    scheduleMobile: "8:30 PM",
    folderValue: 121,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 501,
      name: "Расулжанов Кобулжон",
      image: "/assets/images/avatar/A113.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(1),
    status: 1001,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Rameshwar Sharma",
        image: "/assets/images/avatar/A13.jpg",
        date: getCurrentMonthDate(17),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 234546,
    title: "Arrange a trip for best performing staff members",
    priority: { id: 4354454, name: "Низкий", type: 3, color: green[5] },
    isStarred: true,
    isReplied: false,
    label: [],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(5),
    endDate: getCurrentMonthDate(8),
    scheduleMobile: "9:30 PM",
    folderValue: 121,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 502,
      name: "Бекмирзаев Жасурбек",
      image: "/assets/images/avatar/A114.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(2),
    status: 1002,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Tushar Sharma",
        image: "/assets/images/avatar/A15.jpg",
        date: getCurrentMonthDate(24),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 432445554,
    title: "Check the documents of audit",
    priority: { id: 4545554, name: "Высокий", type: 1, color: red[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
      {
        id: 214,
        name: "openInfo/ModeratorMode",
        alias: "node",
        label: "Node.js",
        value: "Node.js",
        color: grey[5],
      },
    ],
    isAttachment: true,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(20),
    endDate: getCurrentMonthDate(22),
    scheduleMobile: "3:30 PM",
    folderValue: 121,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 503,
      name: "Каримов Диербек",
      image: "/assets/images/avatar/A115.jpg",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(18),
    status: 1003,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "shreyas Iyer",
        image: "/assets/images/avatar/A9.jpg",
        date: getCurrentMonthDate(22),
        time: "4:18am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 455643,
    title: "Check the documents of audit",
    priority: { id: 4545554, name: "Высокий", type: 1, color: red[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 213,
        name: "New Openinfo",
        alias: "jquery",
        label: "JQuery",
        value: "JQuery",
        color: green[5],
      },
    ],
    isAttachment: true,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(4),
    endDate: getCurrentMonthDate(7),
    scheduleMobile: "7:30 PM",
    folderValue: 121,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 503,
      name: "Абдуганиев Отабек",
      image: "/assets/images/avatar/A111.jpg",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(1),
    status: 1003,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Rohit Sharma",
        image: "/assets/images/avatar/A22.jpg",
        date: getCurrentMonthDate(25),
        time: "4:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 856121,
    title: "Arrange birthday party for the staff",
    priority: { id: 9384234, name: "Средний", type: 2, color: blue[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 211,
        name: "E.docs",
        alias: "html",
        label: "Html",
        value: "Html",
        color: red[5],
      },
      {
        id: 212,
        name: "Admin Panel",
        alias: "css",
        label: "CSS",
        value: "CSS",
        color: blue[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(3),
    endDate: getCurrentMonthDate(5),
    scheduleMobile: "8:30 PM",
    folderValue: 121,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 501,
      name: "Зарифбоев Абдулазиз",
      image: "/assets/images/avatar/A112.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(2),
    status: 1001,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Rameshwar Sharma",
        image: "/assets/images/avatar/A13.jpg",
        date: getCurrentMonthDate(17),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 2344354334,
    title: "Download freebie Hello Tune plugin",
    priority: { id: 4545554, name: "Высокий", type: 1, color: red[5] },
    isStarred: true,
    isReplied: false,
    label: [
      {
        id: 212,
        name: "Admin Panel",
        alias: "css",
        label: "CSS",
        value: "CSS",
        color: blue[5],
      },
      {
        id: 214,
        name: "openInfo/ModeratorMode",
        alias: "node",
        label: "Node.js",
        value: "Node.js",
        color: grey[5],
      },
    ],
    isAttachment: false,
    sentAt: "10.30am",
    folderValue: 125,
    startDate: getCurrentMonthDate(20),
    endDate: getCurrentMonthDate(22),
    scheduleMobile: "5:30 PM",
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 504,
      name: "Расулжанов Кобулжон",
      image: "/assets/images/avatar/A113.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(18),
    status: 1001,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Bhuvneshwar Kumar",
        image: "/assets/images/avatar/A10.jpg",
        date: getCurrentMonthDate(18),
        time: "4:18am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 233346,
    title: "Arrange a trip for best performing staff members",
    priority: { id: 4354454, name: "Низкий", type: 3, color: green[5] },
    isStarred: true,
    isReplied: false,
    label: [],
    isAttachment: false,
    sentAt: "10.30am",
    startDate: getCurrentMonthDate(2),
    endDate: getCurrentMonthDate(5),
    scheduleMobile: "6:30 PM",
    folderValue: 121,
    image: "/assets/images/dummy2.jpg",
    assignedTo: {
      id: 502,
      name: "Бекмирзаев Жасурбек",
      image: "/assets/images/avatar/A114.png",
    },
    createdBy: {
      name: "Франк Сергей",
      image: "/assets/images/avatar/A11.png",
    },
    createdOn: getCurrentMonthDate(1),
    status: 1002,
    comments: [
      {
        comment:
          "Call John at 8:00 PM to cross check the things and get a feedback too.",
        name: "Tushar Sharma",
        image: "/assets/images/avatar/A15.jpg",
        date: getCurrentMonthDate(24),
        time: "2:05am",
      },
    ],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
];
export default todoList;
