import { blue, green, grey, red } from "@ant-design/colors";
import { getCurrentMonthDate } from "@crema/helpers/DateHelper";
import { TodoObjType } from "@crema/types/models/apps/Todo";

const useTodoList = (): TodoObjType[] => {

  const todoList: TodoObjType[] = [
    {
      id: 1,
      title: "topleader.task1",
      priority: { id: 101, name: "todo.priority.1", type: 1, color: red[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 213,
          name: "New Openinfo",
          alias: "jquery",
          label: "JQuery",
          value: "JQuery",
          color: green[5],
        },
      ],
      isAttachment: true,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(29),
      endDate: getCurrentMonthDate(31),
      scheduleMobile: "5:30 PM",
      folderValue: 121,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 503,
        name: "Абдуганиев Отабек",
        image: "/assets/images/avatar/A111.jpg",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(26),
      status: 1003,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Rohit Sharma",
          image: "/assets/images/avatar/A22.jpg",
          date: getCurrentMonthDate(30),
          time: "2:05am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 2,
      title: "topleader.task2",
      priority: { id: 102, name: "todo.priority.2", type: 2, color: blue[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 213,
          name: "New Openinfo",
          alias: "jquery",
          label: "JQuery",
          value: "JQuery",
          color: green[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(3),
      endDate: getCurrentMonthDate(6),
      scheduleMobile: "8:30 PM",
      folderValue: 124,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 505,
        name: "Зарифбоев Абдулазиз",
        image: "/assets/images/avatar/A112.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(18),
      status: 1002,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Narendra Kumar",
          image: "/assets/images/avatar/A11.jpg",
          date: "Dec 21, 2021",
          time: "4:18am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 3,
      title: "topleader.task3",
      isStarred: true,
      label: [
        {
          id: 211,
          name: "E.docs",
          alias: "html",
          label: "Html",
          value: "Html",
          color: red[5],
        },
        {
          id: 212,
          name: "Admin Panel",
          alias: "css",
          label: "CSS",
          value: "CSS",
          color: blue[5],
        },
      ],
      priority: { id: 103, name: "todo.priority.1", type: 1, color: red[5] as string},
      isAttachment: false,
      sentAt: "10.30am",
      folderValue: 121,
      startDate: getCurrentMonthDate(18),
      endDate: getCurrentMonthDate(22),
      scheduleMobile: "8:30 PM",
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 501,
        name: "Расулжанов Кобулжон",
        image: "/assets/images/avatar/A113.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(12),
      status: 1001,
      comments: [
        {
          comment:
            "The Task is very important, try to complete it so that we have time for testing.",
          name: "K L Sharma",
          image: "/assets/images/avatar/A21.jpg",
          date: getCurrentMonthDate(20),
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 4,
      title: "topleader.task4",
      isStarred: true,
      label: [
        {
          id: 211,
          name: "E.docs",
          alias: "html",
          label: "Html",
          value: "Html",
          color: red[5],
        },
        {
          id: 212,
          name: "Admin Panel",
          alias: "css",
          label: "CSS",
          value: "CSS",
          color: blue[5],
        },
      ],
      priority: { id: 104, name: "todo.priority.1", type: 1, color: red[5] as string},
      isAttachment: false,
      sentAt: "10.30am",
      folderValue: 121,
      startDate: getCurrentMonthDate(30),
      endDate: getCurrentMonthDate(1),
      scheduleMobile: "8:30 PM",
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 501,
        name: "Бекмирзаев Жасурбек",
        image: "/assets/images/avatar/A114.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(26),
      status: 1001,
      comments: [
        {
          comment:
            "The Task is very important, try to complete it so that we have time for testing.",
          name: "K L Sharma",
          image: "/assets/images/avatar/A21.jpg",
          date: getCurrentMonthDate(28),
          time: "2:05am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 5,
      title: "topleader.task5",
      priority: { id: 105, name: "todo.priority.2", type: 2, color: blue[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 213,
          name: "New Openinfo",
          alias: "jquery",
          label: "JQuery",
          value: "JQuery",
          color: green[5],
        },
        {
          id: 211,
          name: "E.docs",
          alias: "html",
          label: "Html",
          value: "Html",
          color: red[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(19),
      endDate: getCurrentMonthDate(22),
      scheduleMobile: "7:30 PM",
      folderValue: 123,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 502,
        name: "Каримов Диербек",
        image: "/assets/images/avatar/A115.jpg",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(10),
      status: 1002,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "M S Dhoni",
          image: "/assets/images/avatar/A1.jpg",
          date: getCurrentMonthDate(25),
          time: "2:05am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 6,
      title: "topleader.task6",
      priority: { id: 106, name: "todo.priority.2", type: 2, color: blue[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 213,
          name: "New Openinfo",
          alias: "jquery",
          label: "JQuery",
          value: "JQuery",
          color: green[5],
        },
        {
          id: 211,
          name: "E.docs",
          alias: "html",
          label: "Html",
          value: "Html",
          color: red[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(9),
      endDate: getCurrentMonthDate(12),
      scheduleMobile: "7:30 PM",
      folderValue: 123,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 502,
        name: "Абдуганиев Отабек",
        image: "/assets/images/avatar/A111.jpg",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(26),
      status: 1002,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "M S Dhoni",
          image: "/assets/images/avatar/A1.jpg",
          date: getCurrentMonthDate(28),
          time: "2:05am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 7,
      title: "topleader.task7",
      priority: { id: 107, name: "todo.priority.0", type: 3, color: green[5] as string },
      isStarred: false,
      isReplied: false,
      label: [
        {
          id: 214,
          name: "openInfo/ModeratorMode",
          alias: "node",
          label: "Node.js",
          value: "Node.js",
          color: grey[5],
        },
      ],
      isAttachment: true,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(2),
      endDate: getCurrentMonthDate(4),
      scheduleMobile: "6:30 PM",
      isRead: true,
      folderValue: 124,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 503,
        name: "Зарифбоев Абдулазиз",
        image: "/assets/images/avatar/A112.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(19),
      status: 1003,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Nikit Sharma",
          image: "/assets/images/avatar/A2.jpg",
          date: getCurrentMonthDate(21),
          time: "2:15am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 8,
      title: "topleader.task8",
      priority: { id: 108, name: "todo.priority.0", type: 3, color: green[5] as string},
      isStarred: false,
      isReplied: false,
      label: [
        {
          id: 214,
          name: "openInfo/ModeratorMode",
          alias: "node",
          label: "Node.js",
          value: "Node.js",
          color: grey[5],
        },
      ],
      isAttachment: true,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(6),
      endDate: getCurrentMonthDate(12),
      scheduleMobile: "4:30 PM",
      isRead: true,
      folderValue: 124,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 503,
        name: "Расулжанов Кобулжон",
        image: "/assets/images/avatar/A113.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(25),
      status: 1003,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Nikit Sharma",
          image: "/assets/images/avatar/A2.jpg",
          date: getCurrentMonthDate(27),
          time: "2:05am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 9,
      title: "topleader.task9",
      priority: { id: 109, name: "todo.priority.2", type: 2, color: blue[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 211,
          name: "E.docs",
          alias: "html",
          label: "Html",
          value: "Html",
          color: red[5],
        },
        {
          id: 213,
          name: "New Openinfo",
          alias: "jquery",
          label: "JQuery",
          value: "JQuery",
          color: green[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(15),
      endDate: getCurrentMonthDate(18),
      scheduleMobile: "5:30 PM",
      folderValue: 211,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 504,
        name: "Бекмирзаев Жасурбек",
        image: "/assets/images/avatar/A114.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(12),
      status: 1001,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Ravindra Jadeja",
          image: "/assets/images/avatar/A4.jpg",
          date: getCurrentMonthDate(22),
          time: "2:35am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 10,
      title: "topleader.task10",
      priority: { id: 110, name: "todo.priority.2", type: 2, color: blue[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 211,
          name: "E.docs",
          alias: "html",
          label: "Html",
          value: "Html",
          color: red[5],
        },
        {
          id: 213,
          name: "New Openinfo",
          alias: "jquery",
          label: "JQuery",
          value: "JQuery",
          color: green[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(26),
      endDate: getCurrentMonthDate(29),
      scheduleMobile: "8:30 PM",
      folderValue: 211,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 504,
        name: "Каримов Диербек",
        image: "/assets/images/avatar/A115.jpg",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(22),
      status: 1001,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Ravindra Jadeja",
          image: "/assets/images/avatar/A4.jpg",
          date: getCurrentMonthDate(26),
          time: "4:18am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 11,
      title: "topleader.task11",
      priority: { id: 111, name: "todo.priority.1", type: 1, color: red[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 213,
          name: "New Openinfo",
          alias: "jquery",
          label: "JQuery",
          value: "JQuery",
          color: green[5],
        },
        {
          id: 212,
          name: "Admin Panel",
          alias: "css",
          label: "CSS",
          value: "CSS",
          color: blue[5],
        },
      ],
      isAttachment: true,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(13),
      endDate: getCurrentMonthDate(15),
      scheduleMobile: "9:30 PM",
      folderValue: 121,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 505,
        name: "Абдуганиев Отабек",
        image: "/assets/images/avatar/A111.jpg",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(9),
      status: 1002,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Krishna Kumar",
          image: "/assets/images/avatar/A5.jpg",
          date: getCurrentMonthDate(19),
          time: "2:45am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 12,
      title: "topleader.task12",
      priority: { id: 112, name: "todo.priority.0", type: 3, color: green[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 212,
          name: "Admin Panel",
          alias: "css",
          label: "CSS",
          value: "CSS",
          color: blue[5],
        },
        {
          id: 214,
          name: "openInfo/ModeratorMode",
          alias: "node",
          label: "Node.js",
          value: "Node.js",
          color: grey[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(13),
      endDate: getCurrentMonthDate(15),
      scheduleMobile: "8:30 PM",
      folderValue: 126,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 506,
        name: "Зарифбоев Абдулазиз",
        image: "/assets/images/avatar/A112.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(8),
      status: 1003,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Rehan Kant",
          image: "/assets/images/avatar/A6.jpg",
          date: getCurrentMonthDate(18),
          time: "10:05am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 13,
      title: "topleader.task13",
      priority: { id: 113, name: "todo.priority.1", type: 1, color: red[5]as string },
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 213,
          name: "New Openinfo",
          alias: "jquery",
          label: "JQuery",
          value: "JQuery",
          color: green[5],
        },
        {
          id: 212,
          name: "Admin Panel",
          alias: "css",
          label: "CSS",
          value: "CSS",
          color: blue[5],
        },
      ],
      isAttachment: true,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(23),
      endDate: getCurrentMonthDate(25),
      scheduleMobile: "7:30 PM",
      folderValue: 121,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 505,
        name: "Расулжанов Кобулжон",
        image: "/assets/images/avatar/A113.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(22),
      status: 1002,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Krishna Kumar",
          image: "/assets/images/avatar/A5.jpg",
          date: getCurrentMonthDate(26),
          time: "4:18am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 14,
      title: "topleader.task14",
      priority: { id: 114, name: "todo.priority.2", type: 2, color: blue[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 211,
          name: "E.docs",
          alias: "html",
          label: "Html",
          value: "Html",
          color: red[5],
        },
        {
          id: 213,
          name: "New Openinfo",
          alias: "jquery",
          label: "JQuery",
          value: "JQuery",
          color: green[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(12),
      endDate: getCurrentMonthDate(15),
      scheduleMobile: "7:30 PM",
      folderValue: 124,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 501,
        name: "Бекмирзаев Жасурбек",
        image: "/assets/images/avatar/A114.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(7),
      status: 1001,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Rahul Rajan",
          image: "/assets/images/avatar/A7.jpg",
          date: getCurrentMonthDate(21),
          time: "7:05am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 15,
      title: "topleader.task15",
      priority: { id: 115, name: "todo.priority.0", type: 3, color: green[5] as string},
      isStarred: false,
      isReplied: false,
      label: [
        {
          id: 214,
          name: "openInfo/ModeratorMode",
          alias: "node",
          label: "Node.js",
          value: "Node.js",
          color: grey[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(12),
      endDate: getCurrentMonthDate(14),
      scheduleMobile: "5:30 PM",
      folderValue: 125,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 502,
        name: "Каримов Диербек",
        image: "/assets/images/avatar/A115.jpg",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(7),
      status: 1002,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Shikhar Dhawan",
          image: "/assets/images/avatar/A8.jpg",
          date: getCurrentMonthDate(22),
          time: "2:12am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 16,
      title: "topleader.task16",
      priority: { id: 116, name: "todo.priority.0", type: 3, color: green[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 212,
          name: "Admin Panel",
          alias: "css",
          label: "CSS",
          value: "CSS",
          color: blue[5],
        },
        {
          id: 214,
          name: "openInfo/ModeratorMode",
          alias: "node",
          label: "Node.js",
          value: "Node.js",
          color: grey[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(24),
      endDate: getCurrentMonthDate(26),
      scheduleMobile: "7:30 PM",
      folderValue: 126,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 506,
        name: "Абдуганиев Отабек",
        image: "/assets/images/avatar/A111.jpg",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(22),
      status: 1003,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Rehan Kant",
          image: "/assets/images/avatar/A6.jpg",
          date: getCurrentMonthDate(18),
          time: "4:18am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 17,
      title: "topleader.task17",
      priority: { id: 117, name: "todo.priority.1", type: 1, color: red[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 211,
          name: "E.docs",
          alias: "html",
          label: "Html",
          value: "Html",
          color: red[5],
        },
        {
          id: 214,
          name: "openInfo/ModeratorMode",
          alias: "node",
          label: "Node.js",
          value: "Node.js",
          color: grey[5],
        },
      ],
      isAttachment: true,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(10),
      endDate: getCurrentMonthDate(12),
      scheduleMobile: "4:30 PM",
      folderValue: 121,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 503,
        name: "Зарифбоев Абдулазиз",
        image: "/assets/images/avatar/A112.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(6),
      status: 1003,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "shreyas Iyer",
          image: "/assets/images/avatar/A9.jpg",
          date: getCurrentMonthDate(18),
          time: "2:05am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 18,
      title: "topleader.task18",
      priority: { id: 118, name: "todo.priority.1", type: 1, color: red[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 212,
          name: "Admin Panel",
          alias: "css",
          label: "CSS",
          value: "CSS",
          color: blue[5],
        },
        {
          id: 214,
          name: "openInfo/ModeratorMode",
          alias: "node",
          label: "Node.js",
          value: "Node.js",
          color: grey[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      folderValue: 125,
      startDate: getCurrentMonthDate(9),
      endDate: getCurrentMonthDate(10),
      scheduleMobile: "8:30 PM",
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 504,
        name: "Расулжанов Кобулжон",
        image: "/assets/images/avatar/A113.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(1),
      status: 1001,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Bhuvneshwar Kumar",
          image: "/assets/images/avatar/A10.jpg",
          date: getCurrentMonthDate(18),
          time: "2:55am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 19,
      title: "topleader.task19",
      priority: { id: 119, name: "todo.priority.2", type: 2, color: blue[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 211,
          name: "E.docs",
          alias: "html",
          label: "Html",
          value: "Html",
          color: red[5],
        },
        {
          id: 213,
          name: "New Openinfo",
          alias: "jquery",
          label: "JQuery",
          value: "JQuery",
          color: green[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(23),
      endDate: getCurrentMonthDate(26),
      scheduleMobile: "6:30 PM",
      folderValue: 124,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 501,
        name: "Бекмирзаев Жасурбек",
        image: "/assets/images/avatar/A114.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(18),
      status: 1001,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Rahul Rajan",
          image: "/assets/images/avatar/A7.jpg",
          date: getCurrentMonthDate(24),
          time: "4:18am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 20,
      title: "topleader.task20",
      priority: { id: 120, name: "todo.priority.2", type: 2, color: blue[5] as string},
      isStarred: true,
      isReplied: false,
      label: [
        {
          id: 213,
          name: "New Openinfo",
          alias: "jquery",
          label: "JQuery",
          value: "JQuery",
          color: green[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(8),
      endDate: getCurrentMonthDate(10),
      scheduleMobile: "6:30 PM",
      folderValue: 124,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 505,
        name: "Каримов Диербек",
        image: "/assets/images/avatar/A115.jpg",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(5),
      status: 1002,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Narendra Kumar",
          image: "/assets/images/avatar/A11.jpg",
          date: getCurrentMonthDate(18),
          time: "2:05am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 21,
      title: "topleader.task21",
      priority: { id: 121, name: "todo.priority.0", type: 3, color: green[5] as string},
      isStarred: false,
      isReplied: false,
      label: [],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(2),
      endDate: getCurrentMonthDate(5),
      scheduleMobile: "6:30 PM",
      folderValue: 123,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 506,
        name: "Абдуганиев Отабек",
        image: "/assets/images/avatar/A111.jpg",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(2),
      status: 1003,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Baichang Bhutia",
          image: "/assets/images/avatar/A13.jpg",
          date: getCurrentMonthDate(22),
          time: "2:05am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
    {
      id: 22,
      title: "topleader.task22",
      priority: { id: 122, name: "todo.priority.0", type: 3, color: green[5] as string},
      isStarred: false,
      isReplied: false,
      label: [
        {
          id: 214,
          name: "openInfo/ModeratorMode",
          alias: "node",
          label: "Node.js",
          value: "Node.js",
          color: grey[5],
        },
      ],
      isAttachment: false,
      sentAt: "10.30am",
      startDate: getCurrentMonthDate(1),
      endDate: getCurrentMonthDate(2),
      scheduleMobile: "5:30 PM",
      folderValue: 125,
      image: "/assets/images/dummy2.jpg",
      assignedTo: {
        id: 502,
        name: "Зарифбоев Абдулазиз",
        image: "/assets/images/avatar/A112.png",
      },
      createdBy: {
        name: "Франк Сергей",
        image: "/assets/images/avatar/A11.png",
      },
      createdOn: getCurrentMonthDate(21),
      status: 1002,
      comments: [
        {
          comment:
            "Call John at 8:00 PM to cross check the things and get a feedback too.",
          name: "Shikhar Dhawan",
          image: "/assets/images/avatar/A8.jpg",
          date: getCurrentMonthDate(25),
          time: "4:18am",
        },
      ],
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    },
  ];
  return todoList;
};

export default useTodoList;





